-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkReK75YXnPzBaVWH
UkGNDkD3bk47mII7+ANTTjymosSgCgYIKoZIzj0DAQehRANCAAS6DW1cBgBXBCWP
aeCVEiZcaftFLGJvuusVIIxLjHG2yBC2IZoyqmGHsYsQR5EKCJK7iWi42WG0lMEe
L1pfQ0pu
-----END PRIVATE KEY-----